name: latest-blog-post-workflow # 推送指定平台博客信息到workflow
on:
  schedule:
    # 定时器配置
    - cron: "* 5 * * *" # 0 * * * *
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "5" # 获取链接数量
          feed_list: "https://blog.holic-x.com/wv-blog/atom.xml" # 博客订阅地址(RSS格式/Atom格式)